global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'algorips'
    static_configs:
      - targets: ['algorips:8000']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
