FROM python:3.10-slim AS builder
WORKDIR /plugins
COPY plugins/requirements.txt ./
RUN pip wheel --wheel-dir /wheels -r requirements.txt

FROM python:3.10-slim
WORKDIR /plugins
COPY --from=builder /wheels /wheels
COPY plugins/requirements.txt ./
RUN pip install --no-index --find-links=/wheels -r requirements.txt
COPY plugins ./
CMD ["python", "-m", "plugins"]
