name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: gui
      - run: npm test
        working-directory: gui
      - run: python -m pip install -r requirements.txt
      - run: flake8 algorips tests
      - run: pytest -m "not integration" --cov=algorips
      - run: pytest -m integration
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage
