name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: algorips
        ports:
          - 3306:3306
        options: >-
          --health-cmd='mysqladmin ping --silent'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          for d in plugins/*; do
            if [ -f "$d/setup.py" ]; then
              pip install -e "$d"
            fi
          done
      - name: Lint
        run: flake8
      - name: Run tests
        run: pytest --cov=algorips --cov-report=term-missing
