name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker images
        run: docker compose -f docker-compose.prod.yml build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        method: [compose, k8s]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy application
        run: |
          if [ "${{ matrix.method }}" = "compose" ]; then
            docker compose -f docker-compose.prod.yml up -d
          else
            kubectl apply -f k8s/
          fi
