name: Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install audit tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit bandit
      - name: Run pip-audit
        run: pip-audit
      - name: Run bandit
        run: bandit -r algorips -x tests

  notify-failures:
    needs: security-audit
    runs-on: ubuntu-latest
    steps:
      - name: Alert via Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: '{"text":"Security workflow failed."}'
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
