name: Security and Performance

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: algorips
        ports:
          - 3306:3306
        options: >-
          --health-cmd='mysqladmin ping --silent'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          for d in plugins/*; do
            if [ -f "$d/setup.py" ]; then
              pip install -e "$d"
            fi
          done
      - name: Run performance tests
        run: |
          locust -f tests/performance/locustfile.py --headless -u 60 -r 10 -t 1m --csv=perf
          pytest tests/benchmarks --benchmark-only
      - name: Security scan
        run: |
          bandit -r . -lll
          pip-audit -r requirements.txt --severity HIGH

